---
- name: Setup Kali VM with my preferred toolset
  become: true
  become_method: ansible.builtin.sudo
  hosts: all
  vars_files:
    - vars.yml
  vars:
    home_dir: "/home/{{ user }}"
    user: vagrant
  tasks:
    - ansible.builtin.import_tasks: tasks/apt.yml
    # - name: Setup tmux plugin manager
    #   ansible.builtin.git:
    #     clone: true
    #     repo: https://github.com/tmux-plugins/tpm.git
    #     dest: "{{ home_dir }}/.tmux/plugins/tpm"
    #     update: true
    #   become: true
    #   become_user: "{{ user }}"

    - name: Copy the tmux config
      ansible.builtin.copy:
        src: "./files/tmux/tmux.conf"
        dest: "{{ home_dir }}/.tmux.conf"
        owner: "{{ user }}"
        force: true
        mode: "0644"

    - name: Create tmux log directory
      ansible.builtin.file:
        path: "{{ home_dir }}/.tmux-logs"
        state: directory
        owner: "{{ user }}"
        group:  "{{ user }}"
        mode: "0755"

    - name: Create Pipx home directory
      ansible.builtin.file:
        path: /usr/local/share/pipx
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Install cookiecutter and tmuxp
      community.general.pipx:
        name: "{{ item }}"
        state: latest
      environment:
        PIPX_HOME: /usr/local/share/pipx
        PIPX_BIN_DIR: /usr/local/bin
      loop:
        - cookiecutter
        - tmuxp

    - name: Download cookiecutter template
      ansible.builtin.git:
        repo: https://github.com/DerpGusta/cookiecutter-pentest.git
        clone: true
        depth: 1
        dest: "{{ home_dir }}/cookiecutter-pentest"
      become: true
      become_user: "{{ user }}"

    - name: Setup default project
      ansible.builtin.command:
        cmd: "cookiecutter cookiecutter-pentest --no-input"
        creates: "{{ home_dir }}/default"
      become_user: "{{ user }}"

    - name: Setup vpn profile
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ home_dir }}"
        mode: "0644"
        owner: "{{ user }}"
      loop:
        - "files/universal.ovpn" # Offsec
        - "files/academy-regular.ovpn" # HTB

    - name: Setting up required directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: "{{ user }}"
        group: "{{ user }}"
      loop:
        - "{{ home_dir }}/.config/qterminal.org/"
        - "{{ home_dir }}/.config/xfce4/xfconf/xfce-perchannel-xml/"
    - name: Setup terminal settings
      ansible.builtin.copy:
        src: "./files/qterminal.ini"
        dest: "{{ home_dir}}/.config/qterminal.org/"
        force: true
        mode: "0644"
        owner: "{{ user }}"
    - name: Setup xfce specific settings
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ home_dir}}/.config/xfce4/xfconf/xfce-perchannel-xml/"
        force: true
        mode: "0644"
        owner: "{{ user }}"
      loop:
        - "./files/xsettings.xml"
        - "./files/xfce4-power-manager.xml"
    - name: Setup env vars
      ansible.builtin.lineinfile:
        path: "{{ home_dir }}/.zshrc"
        regexp: ".*LANG=C.UTF-8.*"
        line: |
          export LANG=C.UTF-8
        state: present
    - name: Setup zoxide shell config
      ansible.builtin.lineinfile:
        path: "{{ home_dir }}/.zshrc"
        regexp: ".*zoxide init zsh.*" 
        line: |
          eval "$(zoxide init zsh)"
        state: present
    - ansible.builtin.import_tasks: tasks/naabu.yml
